# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F1Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

#import các thư viện tự định nghĩa
from FCeasar import Ui_Ceasarform
from FVigenere import Ui_Vignereform
from FTrithemius import Ui_Trithemiusform
from FBelasco import Ui_Belascoform
from FMotdong import Ui_motdongform
from FNhieudong import Ui_Nhieudongform
from FXORCeasar import Ui_XORCeasar
from FXORVigenere import Ui_XORVignere
from FXORTrithemius import Ui_XORTrithemius
from FXORBelasco import Ui_XORbelascoform
from FSDES import *


class Ui_Mainwindow(object):
    def setupUi(self, Mainwindow):
        Mainwindow.setObjectName("Mainwindow")
        Mainwindow.resize(1127, 744)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("tainguyen/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Mainwindow.setWindowIcon(icon)
        Mainwindow.setWindowOpacity(1.0)
        Mainwindow.setStyleSheet("\n"
"color:black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F6BE5E, stop:0.25 #F8C976, stop:0.5 #FAD794, stop:0.75 #FCE3B4, stop:1 #FDF1D4);\n"
"")
        self.centralwidget = QtWidgets.QWidget(Mainwindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.H1 = QtWidgets.QLabel(self.centralwidget)
        self.H1.setGeometry(QtCore.QRect(170, 20, 841, 111))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.H1.setFont(font)
        self.H1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.H1.setAutoFillBackground(False)
        self.H1.setStyleSheet("font-size: 22px;\n"
"font: 75 26pt \"Tahoma\";\n"
"border: 3px solid #0099FF;\n"
"\n"
"border-radius: 20px;\n"
"color:black;\n"
"\n"
"\n"
"\n"
"")
        self.H1.setAlignment(QtCore.Qt.AlignCenter)
        self.H1.setObjectName("H1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 310, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 3px solid #0099FF;\n"
"font: 16pt \"Montserrat\";\n"
"border-radius:20px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Btn_Ceasar = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Ceasar.setGeometry(QtCore.QRect(250, 170, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Btn_Ceasar.setFont(font)
        self.Btn_Ceasar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_Ceasar.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: #0099FF;\n"
"    border: 3px solid #FF9933;\n"
"    font: 75 16pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 3px solid #0099FF  ;\n"
"    color:black ;\n"
"}\n"
"")
        self.Btn_Ceasar.setObjectName("Btn_Ceasar")
        self.Btn_Vignere = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Vignere.setGeometry(QtCore.QRect(470, 170, 191, 91))
        self.Btn_Vignere.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_Vignere.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: #0099FF;\n"
"    border: 3px solid #FF9933;\n"
"    font: 75 16pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 3px solid #0099FF  ;\n"
"    color:black ;\n"
"}\n"
"")
        self.Btn_Vignere.setObjectName("Btn_Vignere")
        self.Btn_Trithemius = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Trithemius.setGeometry(QtCore.QRect(690, 170, 191, 91))
        self.Btn_Trithemius.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_Trithemius.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: #0099FF;\n"
"    border: 3px solid #FF9933;\n"
"    font: 75 16pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 3px solid #0099FF  ;\n"
"    color:black ;\n"
"}\n"
"")
        self.Btn_Trithemius.setObjectName("Btn_Trithemius")
        self.Btn_Belasco = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Belasco.setGeometry(QtCore.QRect(910, 170, 191, 91))
        self.Btn_Belasco.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_Belasco.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: #0099FF;\n"
"    border: 3px solid #FF9933;\n"
"    font: 75 16pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 3px solid #0099FF  ;\n"
"    color:black ;\n"
"}\n"
"")
        self.Btn_Belasco.setObjectName("Btn_Belasco")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 450, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 16pt \"Montserrat\";\n"
"border-radius:20px;\n"
"border: 3px solid #0099FF;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.Btn_01dong = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_01dong.setGeometry(QtCore.QRect(250, 310, 411, 91))
        self.Btn_01dong.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_01dong.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: #0099FF;\n"
"    border: 3px solid #FF9933;\n"
"    font: 75 16pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 3px solid #0099FF  ;\n"
"    color:black ;\n"
"}\n"
"")
        self.Btn_01dong.setObjectName("Btn_01dong")
        self.Btn_nhieudong = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_nhieudong.setGeometry(QtCore.QRect(690, 310, 411, 91))
        self.Btn_nhieudong.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_nhieudong.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: #0099FF;\n"
"    border: 3px solid #FF9933;\n"
"    font: 75 16pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 3px solid #0099FF  ;\n"
"    color:black ;\n"
"}\n"
"")
        self.Btn_nhieudong.setObjectName("Btn_nhieudong")
        self.Btn_XORVignere = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_XORVignere.setGeometry(QtCore.QRect(470, 450, 191, 91))
        self.Btn_XORVignere.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_XORVignere.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: #0099FF;\n"
"    border: 3px solid #FF9933;\n"
"    font: 75 16pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 3px solid #0099FF  ;\n"
"    color:black ;\n"
"}\n"
"")
        self.Btn_XORVignere.setObjectName("Btn_XORVignere")
        self.Btn_XORBelasco = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_XORBelasco.setGeometry(QtCore.QRect(910, 450, 191, 91))
        self.Btn_XORBelasco.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_XORBelasco.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: #0099FF;\n"
"    border: 3px solid #FF9933;\n"
"    font: 75 16pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 3px solid #0099FF  ;\n"
"    color:black ;\n"
"}\n"
"")
        self.Btn_XORBelasco.setObjectName("Btn_XORBelasco")
        self.Btn_XORTrithemius = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_XORTrithemius.setGeometry(QtCore.QRect(690, 450, 191, 91))
        self.Btn_XORTrithemius.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_XORTrithemius.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: #0099FF;\n"
"    border: 3px solid #FF9933;\n"
"    font: 75 16pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 3px solid #0099FF  ;\n"
"    color:black ;\n"
"}\n"
"")
        self.Btn_XORTrithemius.setObjectName("Btn_XORTrithemius")
        self.Btn_XORCeasar = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_XORCeasar.setGeometry(QtCore.QRect(250, 450, 191, 91))
        self.Btn_XORCeasar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_XORCeasar.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: #0099FF;\n"
"    border: 3px solid #FF9933;\n"
"    font: 75 16pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 3px solid #0099FF  ;\n"
"    color:black ;\n"
"}\n"
"")
        self.Btn_XORCeasar.setObjectName("Btn_XORCeasar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: 3px solid #0099FF;\n"
"border-radius:20px;\n"
"font: 16pt \"Montserrat\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 590, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: 3px solid #0099FF;\n"
"font: 16pt \"Montserrat\";\n"
"border-radius:20px;\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.Btn_SDES = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_SDES.setGeometry(QtCore.QRect(250, 590, 411, 91))
        self.Btn_SDES.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_SDES.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: #0099FF;\n"
"    border: 3px solid #FF9933;\n"
"    font: 75 16pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 3px solid #0099FF  ;\n"
"    color:black ;\n"
"}\n"
"")
        self.Btn_SDES.setObjectName("Btn_SDES")
        self.Btn_SDES_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_SDES_2.setGeometry(QtCore.QRect(690, 590, 411, 91))
        self.Btn_SDES_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_SDES_2.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: #FF0000;\n"
"    border: 3px solid #FFFF00;\n"
"    font: 75 16pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 3px solid #FF0000;\n"
"    color:red ;\n"
"}\n"
"")
        self.Btn_SDES_2.setObjectName("Btn_SDES_2")
        self.Btn_Ceasar.raise_()
        self.H1.raise_()
        self.label_2.raise_()
        self.Btn_Vignere.raise_()
        self.Btn_Trithemius.raise_()
        self.Btn_Belasco.raise_()
        self.label_3.raise_()
        self.Btn_01dong.raise_()
        self.Btn_nhieudong.raise_()
        self.Btn_XORVignere.raise_()
        self.Btn_XORBelasco.raise_()
        self.Btn_XORTrithemius.raise_()
        self.Btn_XORCeasar.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.Btn_SDES.raise_()
        self.Btn_SDES_2.raise_()
        Mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1127, 26))
        self.menubar.setStyleSheet("background-color:white;\n"
"color: black;")
        self.menubar.setObjectName("menubar")
        Mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Mainwindow)
        self.statusbar.setObjectName("statusbar")
        Mainwindow.setStatusBar(self.statusbar)
        self.actionChuy_n_V = QtWidgets.QAction(Mainwindow)
        self.actionChuy_n_V.setCheckable(False)
        self.actionChuy_n_V.setObjectName("actionChuy_n_V")
        self.actionThay_Th = QtWidgets.QAction(Mainwindow)
        self.actionThay_Th.setObjectName("actionThay_Th")
        self.actionXOR = QtWidgets.QAction(Mainwindow)
        self.actionXOR.setObjectName("actionXOR")
        self.actionTho_t = QtWidgets.QAction(Mainwindow)
        self.actionTho_t.setObjectName("actionTho_t")
        self.actionOpen = QtWidgets.QAction(Mainwindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(Mainwindow)
        self.actionSave.setObjectName("actionSave")
        self.actionWebsite = QtWidgets.QAction(Mainwindow)
        self.actionWebsite.setObjectName("actionWebsite")
        self.actionAbout_us = QtWidgets.QAction(Mainwindow)
        self.actionAbout_us.setObjectName("actionAbout_us")
        self.actionSave_2 = QtWidgets.QAction(Mainwindow)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionTho_t_2 = QtWidgets.QAction(Mainwindow)
        self.actionTho_t_2.setObjectName("actionTho_t_2")

        self.retranslateUi(Mainwindow)
        QtCore.QMetaObject.connectSlotsByName(Mainwindow)

# Viết các hàm chức năng - gọi form
        #gọi cửa sổ Ceasar form
        self.Btn_Ceasar.clicked.connect(self.formCeasar)
        #gọi cửa sổ Vignere form
        self.Btn_Vignere.clicked.connect(self.formVignere)
        #gọi cửa sổ Trithemius form
        self.Btn_Trithemius.clicked.connect(self.formTrithemius)
        #gọi cửa sổ Belasco form
        self.Btn_Belasco.clicked.connect(self.formBelasco)
        #gọi cửa sổ mahoa1dong form
        self.Btn_01dong.clicked.connect(self.formMotdong)
        #gọi cửa sổ mahoanhieudong form
        self.Btn_nhieudong.clicked.connect(self.formNhieuDong)
        #gọi cửa sổ XORCeasar form
        self.Btn_XORCeasar.clicked.connect(self.formXORCeasar)
        #gọi cửa sổ XORVignere form
        self.Btn_XORVignere.clicked.connect(self.formXORVignere)
        #gọi cửa sổ XORTrithemius form
        self.Btn_XORTrithemius.clicked.connect(self.formXORTrithemius)
        #gọi cửa sổ XORBelasco form
        self.Btn_XORBelasco.clicked.connect(self.formXORBelasco)
        #gọi cửa sổ SDES form
        self.Btn_SDES.clicked.connect(self.formSDES)
        #gọi chức năng thoát
        self.Btn_SDES_2.clicked.connect(lambda:self.FExit(Mainwindow)) #thoát

# định nghĩa các hàm gọi form
# gọi cửa sổ Ceasar form
    def formCeasar(self):
        self.Ceasarform = QtWidgets.QMainWindow()
        self.ui = Ui_Ceasarform()
        self.ui.setupUi(self.Ceasarform)
        self.Ceasarform.show()

# gọi cửa sổ Vignere form
    def formVignere(self):
        self.Vignereform = QtWidgets.QMainWindow()
        self.ui = Ui_Vignereform()
        self.ui.setupUi(self.Vignereform)
        self.Vignereform.show()
   
# gọi cửa sổ Trithemius form
    def formTrithemius(self):
        self.Trithemiusform = QtWidgets.QMainWindow()
        self.ui = Ui_Trithemiusform()
        self.ui.setupUi(self.Trithemiusform)
        self.Trithemiusform.show()

# gọi cửa sổ Belasco form
    def formBelasco(self):
        self.Belascoform = QtWidgets.QMainWindow()
        self.ui = Ui_Belascoform()
        self.ui.setupUi(self.Belascoform)
        self.Belascoform.show()

# gọi cửa sổ Motdong form
    def formMotdong(self):
        self.motdongform = QtWidgets.QMainWindow()
        self.ui = Ui_motdongform()
        self.ui.setupUi(self.motdongform)
        self.motdongform.show()

# gọi cửa sổ Nhieudong form
    def formNhieuDong(self):
        self.Nhieudongform = QtWidgets.QMainWindow()
        self.ui = Ui_Nhieudongform()
        self.ui.setupUi(self.Nhieudongform)
        self.Nhieudongform.show()

# gọi cửa sổ XORCeasar form
    def formXORCeasar(self):
        self.XORCeasar = QtWidgets.QMainWindow()
        self.ui = Ui_XORCeasar()
        self.ui.setupUi(self.XORCeasar)
        self.XORCeasar.show()

# gọi cửa sổ XORVignere form
    def formXORVignere(self):
        self.XORVignere = QtWidgets.QMainWindow()
        self.ui = Ui_XORVignere()
        self.ui.setupUi(self.XORVignere)
        self.XORVignere.show()

# gọi cửa sổ XORTrithemius form
    def formXORTrithemius(self):
        self.XORTrithemius = QtWidgets.QMainWindow()
        self.ui = Ui_XORTrithemius()
        self.ui.setupUi(self.XORTrithemius)
        self.XORTrithemius.show()

# gọi cửa sổ XORBelasco form
    def formXORBelasco(self):
        self.XORbelascoform = QtWidgets.QMainWindow()
        self.ui = Ui_XORbelascoform()
        self.ui.setupUi(self.XORbelascoform)
        self.XORbelascoform.show()

# gọi cửa sổ FSDES form
    def formSDES(self):
        self.SDESform = QtWidgets.QMainWindow()
        self.ui = Ui_SDESform()
        self.ui.setupUi(self.SDESform)
        self.SDESform.show()

# gọi hàm FExit()
    def FExit(self,Mainwindow):
        print("FExit")
        Mainwindow.hide()



    def retranslateUi(self, Mainwindow):
        _translate = QtCore.QCoreApplication.translate
        Mainwindow.setWindowTitle(_translate("Mainwindow", "Đồ Án Bảo Mật Hệ Thống Thông Tin"))
        self.H1.setText(_translate("Mainwindow", "CÁC THUẬT TOÁN MÃ HÓA CỔ ĐIỂN"))
        self.label_2.setText(_translate("Mainwindow", "Kỹ Thuật \n"
"Chuyển Vị"))
        self.Btn_Ceasar.setText(_translate("Mainwindow", "Ceasar"))
        self.Btn_Vignere.setText(_translate("Mainwindow", "Vigenere"))
        self.Btn_Trithemius.setText(_translate("Mainwindow", "Trithemius"))
        self.Btn_Belasco.setText(_translate("Mainwindow", "Belasco"))
        self.label_3.setText(_translate("Mainwindow", "Kỹ Thuật \n"
"XOR"))
        self.Btn_01dong.setText(_translate("Mainwindow", "Chuyển Vị 1 Dòng"))
        self.Btn_nhieudong.setText(_translate("Mainwindow", "Chuyển Vị Nhiều Dòng"))
        self.Btn_XORVignere.setText(_translate("Mainwindow", "Vigenere"))
        self.Btn_XORBelasco.setText(_translate("Mainwindow", "Belasco"))
        self.Btn_XORTrithemius.setText(_translate("Mainwindow", "Trithemius"))
        self.Btn_XORCeasar.setText(_translate("Mainwindow", "Ceasar"))
        self.label_4.setText(_translate("Mainwindow", "Kỹ Thuật \n"
"Thay Thế"))
        self.label_5.setText(_translate("Mainwindow", "Mã Hóa\n"
" Hiện Đại"))
        self.Btn_SDES.setText(_translate("Mainwindow", "S-DES"))
        self.Btn_SDES_2.setText(_translate("Mainwindow", "Thoát"))
        self.actionChuy_n_V.setText(_translate("Mainwindow", "Chuyển Vị"))
        self.actionThay_Th.setText(_translate("Mainwindow", "Thay Thế"))
        self.actionXOR.setText(_translate("Mainwindow", "XOR"))
        self.actionTho_t.setText(_translate("Mainwindow", "Thoát"))
        self.actionOpen.setText(_translate("Mainwindow", "Open"))
        self.actionSave.setText(_translate("Mainwindow", "Save"))
        self.actionWebsite.setText(_translate("Mainwindow", "Website"))
        self.actionAbout_us.setText(_translate("Mainwindow", "About us"))
        self.actionSave_2.setText(_translate("Mainwindow", "Save"))
        self.actionTho_t_2.setText(_translate("Mainwindow", "Thoát"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mainwindow = QtWidgets.QMainWindow()
    ui = Ui_Mainwindow()
    ui.setupUi(Mainwindow)
    Mainwindow.show()
    sys.exit(app.exec_())
